### ISSUE TITLE
Please port this to samsung smart tvs

### ISSUE THREAD

**Issue by sunmockyang-youi** [nemzutkovic/Carleton-University-CS-Guide#1]
I can't run this on my Samsung Smart TVs version 0.0.0.6423345621325345, please don't ignore my requests.

- Tit Hardwood

**Comment by jaredwideman** [comment]
Hi Tit,

Please try updating your Samsung Smart Fridge OS to version 0.0.0.6424345621325345 and reboot.

**Comment by nemzutkovic** [comment]
Sorry, but Carleton University does not support Samsung products and has no plans to.
